version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "tests/UDKTests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
