name: Build and test generated UScript with UDK

on: [ workflow_call ]

# TODO: unify GH env vars with local UDKTests env vars somehow.
env:
  UDK_LITE_CACHE: ${{ github.workspace }}/tests/UDKTests/.cache/
  UDK_LITE_TAG: 1.0.0
  UDK_TEST_TIMEOUT: 600

jobs:
  build-and-test-with-udk:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        build_type: [ Debug, Release ]

    steps:
      - name: Check out UMB repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache UDK-Lite release archive
        uses: actions/cache@v3
        id: cache-udk-lite-release
        with:
          path: ${{ env.UDK_LITE_CACHE }}
          key: ${{ matrix.os }}-cache-udk-lite-release-${{ env.UDK_LITE_TAG }}
          restore-keys: ${{ matrix.os }}-cache-udk-lite-release-${{ env.UDK_LITE_TAG }}

      - name: Download UnrealScript generated messages
        uses: actions/download-artifact@v3
        with:
          name: umb-generated-uscript-${{ matrix.os }}-${{ matrix.build_type }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: .\tests\UDKTests\requirements.txt
      - run: pip install -r .\tests\UDKTests\requirements.txt
      - run: python --version

      - name: Run UDK build and test script
        timeout-minutes: 10
        run: python .\tests\UDKTests\setup_udk_build_env.py --no-progress-bar

      - name: Archive UDK build and test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: udk-logs-${{ matrix.os }}-${{ matrix.build_type }}
          path: |
            tests/UDKTests/UDK-Lite/UDKGame/Logs/
