name: Build and test generated UScript with UDK

on: [ workflow_call ]

jobs:
  build-and-test-with-udk:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        build_type: [ Debug, Release ]

    steps:
      - name: Check out UMB repository
        uses: actions/checkout@v4

      - name: Download UnrealScript generated messages
        uses: actions/download-artifact@v3
        with:
          name: umb-generated-uscript-${{ matrix.os }}-${{ matrix.build_type }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: .\tests\UDKTests\requirements.txt
      - run: pip install -r .\tests\UDKTests\requirements.txt
      - run: python --version

      - name: Run UDK build and test script
        run: python .\tests\UDKTests\setup_udk_build_env.py
