name: Build and test generated UScript with UDK

on: [ workflow_call ]

# TODO: unify GH env vars with local UDKTests env vars somehow.
env:
  UDK_LITE_CACHE: ${{ github.workspace }}/tests/UDKTests/.cache/
  UDK_LITE_TAG: 1.0.1
  UDK_USCRIPT_MESSAGE_FILES: ${{ github.workspace }}/build/generated/*.uc
  # Timeout for individual steps in the test script. Not a total timeout.
  UDK_TEST_TIMEOUT: 300
  PYTHONUNBUFFERED: 1
  # https://github.com/actions/runner/issues/382
  ErrorView: NormalView

jobs:
  build-and-test-with-udk:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        build_type: [ Debug, Release ]

    steps:
      - name: Check out UMB repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache UDK-Lite release archive
        uses: actions/cache@v3
        id: cache-udk-lite-release
        with:
          path: |
            ${{ env.UDK_LITE_CACHE }}
            ${{ env.UDK_LITE_CACHE }}/*.json
            ${{ env.UDK_LITE_CACHE }}/*.7z
          key: windows-latest-cache-udk-lite-release-${{ env.UDK_LITE_TAG }}
          restore-keys: windows-latest-cache-udk-lite-release-${{ env.UDK_LITE_TAG }}

      - name: Download UnrealScript generated messages
        uses: actions/download-artifact@v3
        with:
          name: umb-generated-uscript-windows-latest-${{ matrix.build_type }}
          path: build/generated/

      - name: Download UMB executables
        uses: actions/download-artifact@v3
        with:
          name: umb-generator-executable-windows-latest-${{ matrix.build_type }}
          path: build/

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: .\tests\UDKTests\requirements.txt

      - run: pip install -r .\tests\UDKTests\requirements.txt

      - run: python --version

      - name: Cache Windows redistributables
        uses: actions/cache@v3
        id: cache-win-redist
        with:
          path: |
            C:\Temp\VcRedist
            C:\Temp\*.exe
          key: win-cached-redist
          restore-keys: win-cached-redist

      - name: Install VC Redist 2012
        run: .\tests\UDKTests\install_vcredist.ps1
        if: matrix.os != 'self-hosted'

      - name: Install DirectX SDK
        run: .\tests\UDKTests\install_dx_sdk.ps1
        if: matrix.os != 'self-hosted'

      - name: Install DirectX Redist
        run: .\tests\UDKTests\install_dx_redist.ps1
        if: matrix.os != 'self-hosted'

      - name: Run UDK build and test script
        timeout-minutes: 5
        run: >
          python .\tests\UDKTests\setup_udk_build_env.py
          --use-shell
          --add-fw-rules
          --echo-server-path ${{ github.workspace }}/build/umb_echo_server.exe

      - name: Archive UDK build and test logs and artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: udk-logs-${{ matrix.os }}-${{ matrix.build_type }}
          path: |
            tests/UDKTests/UDK-Lite/UDKGame/Logs/*.log
            tests/UDKTests/UDK-Lite/UDKGame/Logs/*.dmp
            tests/UDKTests/UDK-Lite/UDKGame/Logs/
            tests/UDKTests/UDK-Lite/UDKGame/Script/UMB*
            tests/UDKTests/UDK-Lite/UDKGame/Script/Manifest.txt
